spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: false

application:
  name: ChangeLogs
  description: Share your Application chabges to your users
  version: 0.0.1-SNAPSHOT
  license: GNU GPLv3
  License-url: https://github.com/GLinBoy/changelogs-backend/blob/main/LICENSE.md
  github-url: https://github.com/GLinBoy/changelogs-backend