spring:
  profiles:
    active: dev
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: false
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  http:
    encoding:
      force: true
server:
  servlet:
    context-path: "/api/v1"

info:
  app:
    name: ChangeLogs
    description: Share your application changes to your users
    version: 0.0.1-SNAPSHOT
    license: GNU GPLv3
    license-url: https://github.com/GLinBoy/changelogs-backend/blob/main/LICENSE.md
    github-url: https://github.com/GLinBoy/changelogs-backend
